version: '4.12'

services:

  mongo_db:
    container_name: db_container
    image: mongo
    restart: always
    ports:
      - 27017:27017
    volumes:
      - mongo_db:/data/db
    
  api:
    build: .
    ports:
      - 9090:9090
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - mongo_db
volumes:
  mongo_db: {}